# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 693774b93ab148c105f69e79f8f32ba59dd4533ecd7eb81f499fba9e92ce975fdee4060d419ea4b9076ae2533592a4346ba0274d7ab59b623f9b052afcafd086

test:
  secret_key_base: c7286329b584e9207e2ca2fab7fe08d0ee9bf8e973bfc0ecca33ec04692780b1ea5ae372bf35924c69af55e72d3838958fd8f8a1446ac4c14e44777c597e712b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
